### ISSUE TITLE
在 GitHub 上无法使用

### ISSUE THREAD

**Issue by lulucici** [Axure/MathAsYouWill#1]
> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".

**Comment by Axure** [comment]
Fixed in [#aa523a1](https://github.com/Axure/MathAsYouWill/commit/aa523a1830da5f6cc3ace8767bf33d531931b98b).
